#cc_binary(
#    name = "single_agent_test",
#    srcs = [
#        "single_agent_test.cc",
#    ],
#    copts = ["-Iexternal/gtest/include"],
#    deps = [
#        "//bark/models/behavior",
#        "//bark/models/behavior/constant_velocity",
#        "//bark/models/behavior/motion_primitives",
#        "//bark/models/behavior/planner_mcts:planner_mvmcts_single_agent",
#        "//bark/world/tests:make_test_world",
#        "//bark/world",
#        "//bark/world/evaluation:evaluator_collision_ego_agent",
#        "//bark/world/evaluation:evaluator_goal_reached",
#        "//bark/world/evaluation/labels:label_evaluation",
#        "//bark/world/goal_definition",
#        "@gtest//:main",
#    ],
#)
