cc_library(
    name = "label_evaluators",
    srcs = glob(["*.cpp"]),
    hdrs = glob([
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//gridworld:common",
        "@rule_monitor_project//ltl:rule_monitor",
    ],
)
