#cc_binary(
#    name = "label_test",
#    srcs = ["label_test.cpp"],
#    copts = ["-Iexternal/gtest/include"],
#    deps = [
#        "//gridworld/label_evaluator:label_evaluators",
#        "@gtest//:gtest_main",
#    ],
#)